// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package org.example.test;

/**
 * Protobuf type {@code test.Test}
 */
public final class Test extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:test.Test)
    TestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Test.newBuilder() to construct.
  private Test(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Test() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Test();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Test(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              a_ = com.google.protobuf.MapField.newMapField(
                  ADefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            a__ = input.readMessage(
                ADefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            a_.getMutableMap().put(
                a__.getKey(), a__.getValue());
            break;
          }
          case 18: {
            org.example.test.Test.Contents.Builder subBuilder = null;
            if (contents_ != null) {
              subBuilder = contents_.toBuilder();
            }
            contents_ = input.readMessage(org.example.test.Test.Contents.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(contents_);
              contents_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.test.TestOuterClass.internal_static_test_Test_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetA();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.test.TestOuterClass.internal_static_test_Test_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.test.Test.class, org.example.test.Test.Builder.class);
  }

  public interface ContentsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.Test.Contents)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; b = 1;</code>
     */
    int getBCount();
    /**
     * <code>map&lt;string, string&gt; b = 1;</code>
     */
    boolean containsB(
        java.lang.String key);
    /**
     * Use {@link #getBMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getB();
    /**
     * <code>map&lt;string, string&gt; b = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getBMap();
    /**
     * <code>map&lt;string, string&gt; b = 1;</code>
     */

    java.lang.String getBOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; b = 1;</code>
     */

    java.lang.String getBOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code test.Test.Contents}
   */
  public static final class Contents extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.Test.Contents)
      ContentsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Contents.newBuilder() to construct.
    private Contents(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Contents() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Contents();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Contents(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                b_ = com.google.protobuf.MapField.newMapField(
                    BDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              b__ = input.readMessage(
                  BDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              b_.getMutableMap().put(
                  b__.getKey(), b__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.test.TestOuterClass.internal_static_test_Test_Contents_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetB();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.test.TestOuterClass.internal_static_test_Test_Contents_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.test.Test.Contents.class, org.example.test.Test.Contents.Builder.class);
    }

    public static final int B_FIELD_NUMBER = 1;
    private static final class BDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  org.example.test.TestOuterClass.internal_static_test_Test_Contents_BEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> b_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetB() {
      if (b_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            BDefaultEntryHolder.defaultEntry);
      }
      return b_;
    }

    public int getBCount() {
      return internalGetB().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; b = 1;</code>
     */

    @java.lang.Override
    public boolean containsB(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetB().getMap().containsKey(key);
    }
    /**
     * Use {@link #getBMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getB() {
      return getBMap();
    }
    /**
     * <code>map&lt;string, string&gt; b = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getBMap() {
      return internalGetB().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; b = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getBOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetB().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; b = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getBOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetB().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetB(),
          BDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetB().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        b__ = BDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, b__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.test.Test.Contents)) {
        return super.equals(obj);
      }
      org.example.test.Test.Contents other = (org.example.test.Test.Contents) obj;

      if (!internalGetB().equals(
          other.internalGetB())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetB().getMap().isEmpty()) {
        hash = (37 * hash) + B_FIELD_NUMBER;
        hash = (53 * hash) + internalGetB().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.test.Test.Contents parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.test.Test.Contents parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.test.Test.Contents parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.test.Test.Contents parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.test.Test.Contents parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.test.Test.Contents parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.test.Test.Contents parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.test.Test.Contents parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.test.Test.Contents parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.test.Test.Contents parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.test.Test.Contents parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.test.Test.Contents parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.test.Test.Contents prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.Test.Contents}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.Test.Contents)
        org.example.test.Test.ContentsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.test.TestOuterClass.internal_static_test_Test_Contents_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetB();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableB();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.test.TestOuterClass.internal_static_test_Test_Contents_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.test.Test.Contents.class, org.example.test.Test.Contents.Builder.class);
      }

      // Construct using org.example.test.Test.Contents.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableB().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.test.TestOuterClass.internal_static_test_Test_Contents_descriptor;
      }

      @java.lang.Override
      public org.example.test.Test.Contents getDefaultInstanceForType() {
        return org.example.test.Test.Contents.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.test.Test.Contents build() {
        org.example.test.Test.Contents result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.test.Test.Contents buildPartial() {
        org.example.test.Test.Contents result = new org.example.test.Test.Contents(this);
        int from_bitField0_ = bitField0_;
        result.b_ = internalGetB();
        result.b_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.test.Test.Contents) {
          return mergeFrom((org.example.test.Test.Contents)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.test.Test.Contents other) {
        if (other == org.example.test.Test.Contents.getDefaultInstance()) return this;
        internalGetMutableB().mergeFrom(
            other.internalGetB());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.test.Test.Contents parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.test.Test.Contents) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> b_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetB() {
        if (b_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              BDefaultEntryHolder.defaultEntry);
        }
        return b_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableB() {
        onChanged();;
        if (b_ == null) {
          b_ = com.google.protobuf.MapField.newMapField(
              BDefaultEntryHolder.defaultEntry);
        }
        if (!b_.isMutable()) {
          b_ = b_.copy();
        }
        return b_;
      }

      public int getBCount() {
        return internalGetB().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; b = 1;</code>
       */

      @java.lang.Override
      public boolean containsB(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetB().getMap().containsKey(key);
      }
      /**
       * Use {@link #getBMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getB() {
        return getBMap();
      }
      /**
       * <code>map&lt;string, string&gt; b = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getBMap() {
        return internalGetB().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; b = 1;</code>
       */
      @java.lang.Override

      public java.lang.String getBOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetB().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; b = 1;</code>
       */
      @java.lang.Override

      public java.lang.String getBOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetB().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearB() {
        internalGetMutableB().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; b = 1;</code>
       */

      public Builder removeB(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableB().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableB() {
        return internalGetMutableB().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; b = 1;</code>
       */
      public Builder putB(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableB().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; b = 1;</code>
       */

      public Builder putAllB(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableB().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.Test.Contents)
    }

    // @@protoc_insertion_point(class_scope:test.Test.Contents)
    private static final org.example.test.Test.Contents DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.test.Test.Contents();
    }

    public static org.example.test.Test.Contents getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Contents>
        PARSER = new com.google.protobuf.AbstractParser<Contents>() {
      @java.lang.Override
      public Contents parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Contents(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Contents> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Contents> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.test.Test.Contents getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int A_FIELD_NUMBER = 1;
  private static final class ADefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.example.test.TestOuterClass.internal_static_test_Test_AEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> a_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetA() {
    if (a_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ADefaultEntryHolder.defaultEntry);
    }
    return a_;
  }

  public int getACount() {
    return internalGetA().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; a = 1;</code>
   */

  @java.lang.Override
  public boolean containsA(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetA().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getA() {
    return getAMap();
  }
  /**
   * <code>map&lt;string, string&gt; a = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getAMap() {
    return internalGetA().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; a = 1;</code>
   */
  @java.lang.Override

  public java.lang.String getAOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetA().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; a = 1;</code>
   */
  @java.lang.Override

  public java.lang.String getAOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetA().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int CONTENTS_FIELD_NUMBER = 2;
  private org.example.test.Test.Contents contents_;
  /**
   * <code>.test.Test.Contents contents = 2;</code>
   * @return Whether the contents field is set.
   */
  @java.lang.Override
  public boolean hasContents() {
    return contents_ != null;
  }
  /**
   * <code>.test.Test.Contents contents = 2;</code>
   * @return The contents.
   */
  @java.lang.Override
  public org.example.test.Test.Contents getContents() {
    return contents_ == null ? org.example.test.Test.Contents.getDefaultInstance() : contents_;
  }
  /**
   * <code>.test.Test.Contents contents = 2;</code>
   */
  @java.lang.Override
  public org.example.test.Test.ContentsOrBuilder getContentsOrBuilder() {
    return getContents();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetA(),
        ADefaultEntryHolder.defaultEntry,
        1);
    if (contents_ != null) {
      output.writeMessage(2, getContents());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetA().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      a__ = ADefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, a__);
    }
    if (contents_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getContents());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.test.Test)) {
      return super.equals(obj);
    }
    org.example.test.Test other = (org.example.test.Test) obj;

    if (!internalGetA().equals(
        other.internalGetA())) return false;
    if (hasContents() != other.hasContents()) return false;
    if (hasContents()) {
      if (!getContents()
          .equals(other.getContents())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetA().getMap().isEmpty()) {
      hash = (37 * hash) + A_FIELD_NUMBER;
      hash = (53 * hash) + internalGetA().hashCode();
    }
    if (hasContents()) {
      hash = (37 * hash) + CONTENTS_FIELD_NUMBER;
      hash = (53 * hash) + getContents().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.test.Test parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.test.Test parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.test.Test parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.test.Test parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.test.Test parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.test.Test parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.test.Test parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.test.Test parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.test.Test parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.example.test.Test parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.test.Test parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.test.Test parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.test.Test prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code test.Test}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:test.Test)
      org.example.test.TestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.test.TestOuterClass.internal_static_test_Test_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetA();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableA();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.test.TestOuterClass.internal_static_test_Test_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.test.Test.class, org.example.test.Test.Builder.class);
    }

    // Construct using org.example.test.Test.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableA().clear();
      if (contentsBuilder_ == null) {
        contents_ = null;
      } else {
        contents_ = null;
        contentsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.test.TestOuterClass.internal_static_test_Test_descriptor;
    }

    @java.lang.Override
    public org.example.test.Test getDefaultInstanceForType() {
      return org.example.test.Test.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.test.Test build() {
      org.example.test.Test result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.test.Test buildPartial() {
      org.example.test.Test result = new org.example.test.Test(this);
      int from_bitField0_ = bitField0_;
      result.a_ = internalGetA();
      result.a_.makeImmutable();
      if (contentsBuilder_ == null) {
        result.contents_ = contents_;
      } else {
        result.contents_ = contentsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.test.Test) {
        return mergeFrom((org.example.test.Test)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.test.Test other) {
      if (other == org.example.test.Test.getDefaultInstance()) return this;
      internalGetMutableA().mergeFrom(
          other.internalGetA());
      if (other.hasContents()) {
        mergeContents(other.getContents());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.example.test.Test parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.example.test.Test) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> a_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetA() {
      if (a_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ADefaultEntryHolder.defaultEntry);
      }
      return a_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableA() {
      onChanged();;
      if (a_ == null) {
        a_ = com.google.protobuf.MapField.newMapField(
            ADefaultEntryHolder.defaultEntry);
      }
      if (!a_.isMutable()) {
        a_ = a_.copy();
      }
      return a_;
    }

    public int getACount() {
      return internalGetA().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; a = 1;</code>
     */

    @java.lang.Override
    public boolean containsA(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetA().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getA() {
      return getAMap();
    }
    /**
     * <code>map&lt;string, string&gt; a = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getAMap() {
      return internalGetA().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; a = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getAOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetA().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; a = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getAOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetA().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearA() {
      internalGetMutableA().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; a = 1;</code>
     */

    public Builder removeA(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableA().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableA() {
      return internalGetMutableA().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; a = 1;</code>
     */
    public Builder putA(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableA().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; a = 1;</code>
     */

    public Builder putAllA(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableA().getMutableMap()
          .putAll(values);
      return this;
    }

    private org.example.test.Test.Contents contents_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.example.test.Test.Contents, org.example.test.Test.Contents.Builder, org.example.test.Test.ContentsOrBuilder> contentsBuilder_;
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     * @return Whether the contents field is set.
     */
    public boolean hasContents() {
      return contentsBuilder_ != null || contents_ != null;
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     * @return The contents.
     */
    public org.example.test.Test.Contents getContents() {
      if (contentsBuilder_ == null) {
        return contents_ == null ? org.example.test.Test.Contents.getDefaultInstance() : contents_;
      } else {
        return contentsBuilder_.getMessage();
      }
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     */
    public Builder setContents(org.example.test.Test.Contents value) {
      if (contentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        contents_ = value;
        onChanged();
      } else {
        contentsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     */
    public Builder setContents(
        org.example.test.Test.Contents.Builder builderForValue) {
      if (contentsBuilder_ == null) {
        contents_ = builderForValue.build();
        onChanged();
      } else {
        contentsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     */
    public Builder mergeContents(org.example.test.Test.Contents value) {
      if (contentsBuilder_ == null) {
        if (contents_ != null) {
          contents_ =
            org.example.test.Test.Contents.newBuilder(contents_).mergeFrom(value).buildPartial();
        } else {
          contents_ = value;
        }
        onChanged();
      } else {
        contentsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     */
    public Builder clearContents() {
      if (contentsBuilder_ == null) {
        contents_ = null;
        onChanged();
      } else {
        contents_ = null;
        contentsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     */
    public org.example.test.Test.Contents.Builder getContentsBuilder() {
      
      onChanged();
      return getContentsFieldBuilder().getBuilder();
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     */
    public org.example.test.Test.ContentsOrBuilder getContentsOrBuilder() {
      if (contentsBuilder_ != null) {
        return contentsBuilder_.getMessageOrBuilder();
      } else {
        return contents_ == null ?
            org.example.test.Test.Contents.getDefaultInstance() : contents_;
      }
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.example.test.Test.Contents, org.example.test.Test.Contents.Builder, org.example.test.Test.ContentsOrBuilder> 
        getContentsFieldBuilder() {
      if (contentsBuilder_ == null) {
        contentsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.example.test.Test.Contents, org.example.test.Test.Contents.Builder, org.example.test.Test.ContentsOrBuilder>(
                getContents(),
                getParentForChildren(),
                isClean());
        contents_ = null;
      }
      return contentsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:test.Test)
  }

  // @@protoc_insertion_point(class_scope:test.Test)
  private static final org.example.test.Test DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.test.Test();
  }

  public static org.example.test.Test getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Test>
      PARSER = new com.google.protobuf.AbstractParser<Test>() {
    @java.lang.Override
    public Test parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Test(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Test> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Test> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.test.Test getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

