// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package org.example.test;

public final class TestOuterClass {
  private TestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Test_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_Test_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Test_AEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_Test_AEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Test_Contents_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_Test_Contents_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Test_Contents_BEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_Test_Contents_BEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\004test\"\322\001\n\004Test\022\034\n\001a\030\001 \003(\0132\021" +
      ".test.Test.AEntry\022%\n\010contents\030\002 \001(\0132\023.te" +
      "st.Test.Contents\032(\n\006AEntry\022\013\n\003key\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\t:\0028\001\032[\n\010Contents\022%\n\001b\030\001 \003(" +
      "\0132\032.test.Test.Contents.BEntry\032(\n\006BEntry\022" +
      "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\024\n\020org.e" +
      "xample.testP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_test_Test_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_Test_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_Test_descriptor,
        new java.lang.String[] { "A", "Contents", });
    internal_static_test_Test_AEntry_descriptor =
      internal_static_test_Test_descriptor.getNestedTypes().get(0);
    internal_static_test_Test_AEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_Test_AEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_test_Test_Contents_descriptor =
      internal_static_test_Test_descriptor.getNestedTypes().get(1);
    internal_static_test_Test_Contents_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_Test_Contents_descriptor,
        new java.lang.String[] { "B", });
    internal_static_test_Test_Contents_BEntry_descriptor =
      internal_static_test_Test_Contents_descriptor.getNestedTypes().get(0);
    internal_static_test_Test_Contents_BEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_Test_Contents_BEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
