// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package org.example.test;

public interface TestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.Test)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; a = 1;</code>
   */
  int getACount();
  /**
   * <code>map&lt;string, string&gt; a = 1;</code>
   */
  boolean containsA(
      java.lang.String key);
  /**
   * Use {@link #getAMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getA();
  /**
   * <code>map&lt;string, string&gt; a = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAMap();
  /**
   * <code>map&lt;string, string&gt; a = 1;</code>
   */

  java.lang.String getAOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; a = 1;</code>
   */

  java.lang.String getAOrThrow(
      java.lang.String key);

  /**
   * <code>.test.Test.Contents contents = 2;</code>
   * @return Whether the contents field is set.
   */
  boolean hasContents();
  /**
   * <code>.test.Test.Contents contents = 2;</code>
   * @return The contents.
   */
  org.example.test.Test.Contents getContents();
  /**
   * <code>.test.Test.Contents contents = 2;</code>
   */
  org.example.test.Test.ContentsOrBuilder getContentsOrBuilder();
}
