// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/test.proto

package org.example.proto;

public final class TestOuterClass {
  private TestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Test_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_Test_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Test_MapFieldAEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_Test_MapFieldAEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Test_Contents_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_Test_Contents_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_Test_Contents_MapFieldBEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_Test_Contents_MapFieldBEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035src/main/resources/test.proto\022\004test\"\206\002" +
      "\n\004Test\022.\n\013map_field_a\030\001 \003(\0132\031.test.Test." +
      "MapFieldAEntry\022%\n\010contents\030\002 \001(\0132\023.test." +
      "Test.Contents\0320\n\016MapFieldAEntry\022\013\n\003key\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032u\n\010Contents\0227\n\013m" +
      "ap_field_b\030\001 \003(\0132\".test.Test.Contents.Ma" +
      "pFieldBEntry\0320\n\016MapFieldBEntry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\025\n\021org.example.pr" +
      "otoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_test_Test_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_Test_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_Test_descriptor,
        new java.lang.String[] { "MapFieldA", "Contents", });
    internal_static_test_Test_MapFieldAEntry_descriptor =
      internal_static_test_Test_descriptor.getNestedTypes().get(0);
    internal_static_test_Test_MapFieldAEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_Test_MapFieldAEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_test_Test_Contents_descriptor =
      internal_static_test_Test_descriptor.getNestedTypes().get(1);
    internal_static_test_Test_Contents_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_Test_Contents_descriptor,
        new java.lang.String[] { "MapFieldB", });
    internal_static_test_Test_Contents_MapFieldBEntry_descriptor =
      internal_static_test_Test_Contents_descriptor.getNestedTypes().get(0);
    internal_static_test_Test_Contents_MapFieldBEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_Test_Contents_MapFieldBEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
