// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/test.proto

package org.example.proto;

/**
 * Protobuf type {@code test.Test}
 */
public final class Test extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:test.Test)
    TestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Test.newBuilder() to construct.
  private Test(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Test() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Test();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Test(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              mapFieldA_ = com.google.protobuf.MapField.newMapField(
                  MapFieldADefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            mapFieldA__ = input.readMessage(
                MapFieldADefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            mapFieldA_.getMutableMap().put(
                mapFieldA__.getKey(), mapFieldA__.getValue());
            break;
          }
          case 18: {
            org.example.proto.Test.Contents.Builder subBuilder = null;
            if (contents_ != null) {
              subBuilder = contents_.toBuilder();
            }
            contents_ = input.readMessage(org.example.proto.Test.Contents.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(contents_);
              contents_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.proto.TestOuterClass.internal_static_test_Test_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetMapFieldA();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.proto.TestOuterClass.internal_static_test_Test_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.proto.Test.class, org.example.proto.Test.Builder.class);
  }

  public interface ContentsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.Test.Contents)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; map_field_b = 1;</code>
     */
    int getMapFieldBCount();
    /**
     * <code>map&lt;string, string&gt; map_field_b = 1;</code>
     */
    boolean containsMapFieldB(
        java.lang.String key);
    /**
     * Use {@link #getMapFieldBMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMapFieldB();
    /**
     * <code>map&lt;string, string&gt; map_field_b = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMapFieldBMap();
    /**
     * <code>map&lt;string, string&gt; map_field_b = 1;</code>
     */

    java.lang.String getMapFieldBOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; map_field_b = 1;</code>
     */

    java.lang.String getMapFieldBOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code test.Test.Contents}
   */
  public static final class Contents extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.Test.Contents)
      ContentsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Contents.newBuilder() to construct.
    private Contents(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Contents() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Contents();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Contents(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                mapFieldB_ = com.google.protobuf.MapField.newMapField(
                    MapFieldBDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              mapFieldB__ = input.readMessage(
                  MapFieldBDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              mapFieldB_.getMutableMap().put(
                  mapFieldB__.getKey(), mapFieldB__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.TestOuterClass.internal_static_test_Test_Contents_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMapFieldB();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.TestOuterClass.internal_static_test_Test_Contents_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.Test.Contents.class, org.example.proto.Test.Contents.Builder.class);
    }

    public static final int MAP_FIELD_B_FIELD_NUMBER = 1;
    private static final class MapFieldBDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  org.example.proto.TestOuterClass.internal_static_test_Test_Contents_MapFieldBEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> mapFieldB_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMapFieldB() {
      if (mapFieldB_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapFieldBDefaultEntryHolder.defaultEntry);
      }
      return mapFieldB_;
    }

    public int getMapFieldBCount() {
      return internalGetMapFieldB().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; map_field_b = 1;</code>
     */

    @java.lang.Override
    public boolean containsMapFieldB(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMapFieldB().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapFieldBMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMapFieldB() {
      return getMapFieldBMap();
    }
    /**
     * <code>map&lt;string, string&gt; map_field_b = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMapFieldBMap() {
      return internalGetMapFieldB().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; map_field_b = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getMapFieldBOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMapFieldB().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; map_field_b = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getMapFieldBOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMapFieldB().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMapFieldB(),
          MapFieldBDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMapFieldB().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        mapFieldB__ = MapFieldBDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, mapFieldB__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.proto.Test.Contents)) {
        return super.equals(obj);
      }
      org.example.proto.Test.Contents other = (org.example.proto.Test.Contents) obj;

      if (!internalGetMapFieldB().equals(
          other.internalGetMapFieldB())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetMapFieldB().getMap().isEmpty()) {
        hash = (37 * hash) + MAP_FIELD_B_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMapFieldB().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.proto.Test.Contents parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.Test.Contents parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.Test.Contents parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.Test.Contents parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.Test.Contents parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.Test.Contents parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.Test.Contents parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.Test.Contents parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.Test.Contents parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.proto.Test.Contents parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.Test.Contents parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.Test.Contents parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.proto.Test.Contents prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.Test.Contents}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.Test.Contents)
        org.example.proto.Test.ContentsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.proto.TestOuterClass.internal_static_test_Test_Contents_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMapFieldB();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableMapFieldB();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.proto.TestOuterClass.internal_static_test_Test_Contents_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.proto.Test.Contents.class, org.example.proto.Test.Contents.Builder.class);
      }

      // Construct using org.example.proto.Test.Contents.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableMapFieldB().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.proto.TestOuterClass.internal_static_test_Test_Contents_descriptor;
      }

      @java.lang.Override
      public org.example.proto.Test.Contents getDefaultInstanceForType() {
        return org.example.proto.Test.Contents.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.proto.Test.Contents build() {
        org.example.proto.Test.Contents result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.proto.Test.Contents buildPartial() {
        org.example.proto.Test.Contents result = new org.example.proto.Test.Contents(this);
        int from_bitField0_ = bitField0_;
        result.mapFieldB_ = internalGetMapFieldB();
        result.mapFieldB_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.proto.Test.Contents) {
          return mergeFrom((org.example.proto.Test.Contents)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.proto.Test.Contents other) {
        if (other == org.example.proto.Test.Contents.getDefaultInstance()) return this;
        internalGetMutableMapFieldB().mergeFrom(
            other.internalGetMapFieldB());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.proto.Test.Contents parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.proto.Test.Contents) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> mapFieldB_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMapFieldB() {
        if (mapFieldB_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MapFieldBDefaultEntryHolder.defaultEntry);
        }
        return mapFieldB_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableMapFieldB() {
        onChanged();;
        if (mapFieldB_ == null) {
          mapFieldB_ = com.google.protobuf.MapField.newMapField(
              MapFieldBDefaultEntryHolder.defaultEntry);
        }
        if (!mapFieldB_.isMutable()) {
          mapFieldB_ = mapFieldB_.copy();
        }
        return mapFieldB_;
      }

      public int getMapFieldBCount() {
        return internalGetMapFieldB().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; map_field_b = 1;</code>
       */

      @java.lang.Override
      public boolean containsMapFieldB(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMapFieldB().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMapFieldBMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMapFieldB() {
        return getMapFieldBMap();
      }
      /**
       * <code>map&lt;string, string&gt; map_field_b = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getMapFieldBMap() {
        return internalGetMapFieldB().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; map_field_b = 1;</code>
       */
      @java.lang.Override

      public java.lang.String getMapFieldBOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMapFieldB().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; map_field_b = 1;</code>
       */
      @java.lang.Override

      public java.lang.String getMapFieldBOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMapFieldB().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMapFieldB() {
        internalGetMutableMapFieldB().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; map_field_b = 1;</code>
       */

      public Builder removeMapFieldB(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMapFieldB().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableMapFieldB() {
        return internalGetMutableMapFieldB().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; map_field_b = 1;</code>
       */
      public Builder putMapFieldB(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMapFieldB().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; map_field_b = 1;</code>
       */

      public Builder putAllMapFieldB(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableMapFieldB().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.Test.Contents)
    }

    // @@protoc_insertion_point(class_scope:test.Test.Contents)
    private static final org.example.proto.Test.Contents DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.proto.Test.Contents();
    }

    public static org.example.proto.Test.Contents getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Contents>
        PARSER = new com.google.protobuf.AbstractParser<Contents>() {
      @java.lang.Override
      public Contents parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Contents(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Contents> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Contents> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.proto.Test.Contents getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int MAP_FIELD_A_FIELD_NUMBER = 1;
  private static final class MapFieldADefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.example.proto.TestOuterClass.internal_static_test_Test_MapFieldAEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> mapFieldA_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMapFieldA() {
    if (mapFieldA_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MapFieldADefaultEntryHolder.defaultEntry);
    }
    return mapFieldA_;
  }

  public int getMapFieldACount() {
    return internalGetMapFieldA().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; map_field_a = 1;</code>
   */

  @java.lang.Override
  public boolean containsMapFieldA(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetMapFieldA().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMapFieldAMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMapFieldA() {
    return getMapFieldAMap();
  }
  /**
   * <code>map&lt;string, string&gt; map_field_a = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getMapFieldAMap() {
    return internalGetMapFieldA().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; map_field_a = 1;</code>
   */
  @java.lang.Override

  public java.lang.String getMapFieldAOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMapFieldA().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; map_field_a = 1;</code>
   */
  @java.lang.Override

  public java.lang.String getMapFieldAOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMapFieldA().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int CONTENTS_FIELD_NUMBER = 2;
  private org.example.proto.Test.Contents contents_;
  /**
   * <code>.test.Test.Contents contents = 2;</code>
   * @return Whether the contents field is set.
   */
  @java.lang.Override
  public boolean hasContents() {
    return contents_ != null;
  }
  /**
   * <code>.test.Test.Contents contents = 2;</code>
   * @return The contents.
   */
  @java.lang.Override
  public org.example.proto.Test.Contents getContents() {
    return contents_ == null ? org.example.proto.Test.Contents.getDefaultInstance() : contents_;
  }
  /**
   * <code>.test.Test.Contents contents = 2;</code>
   */
  @java.lang.Override
  public org.example.proto.Test.ContentsOrBuilder getContentsOrBuilder() {
    return getContents();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMapFieldA(),
        MapFieldADefaultEntryHolder.defaultEntry,
        1);
    if (contents_ != null) {
      output.writeMessage(2, getContents());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMapFieldA().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      mapFieldA__ = MapFieldADefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mapFieldA__);
    }
    if (contents_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getContents());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.proto.Test)) {
      return super.equals(obj);
    }
    org.example.proto.Test other = (org.example.proto.Test) obj;

    if (!internalGetMapFieldA().equals(
        other.internalGetMapFieldA())) return false;
    if (hasContents() != other.hasContents()) return false;
    if (hasContents()) {
      if (!getContents()
          .equals(other.getContents())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetMapFieldA().getMap().isEmpty()) {
      hash = (37 * hash) + MAP_FIELD_A_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMapFieldA().hashCode();
    }
    if (hasContents()) {
      hash = (37 * hash) + CONTENTS_FIELD_NUMBER;
      hash = (53 * hash) + getContents().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.proto.Test parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.Test parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.Test parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.Test parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.Test parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.proto.Test parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.proto.Test parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.Test parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.proto.Test parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.example.proto.Test parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.proto.Test parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.proto.Test parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.proto.Test prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code test.Test}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:test.Test)
      org.example.proto.TestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.TestOuterClass.internal_static_test_Test_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMapFieldA();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableMapFieldA();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.TestOuterClass.internal_static_test_Test_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.Test.class, org.example.proto.Test.Builder.class);
    }

    // Construct using org.example.proto.Test.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableMapFieldA().clear();
      if (contentsBuilder_ == null) {
        contents_ = null;
      } else {
        contents_ = null;
        contentsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.proto.TestOuterClass.internal_static_test_Test_descriptor;
    }

    @java.lang.Override
    public org.example.proto.Test getDefaultInstanceForType() {
      return org.example.proto.Test.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.proto.Test build() {
      org.example.proto.Test result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.proto.Test buildPartial() {
      org.example.proto.Test result = new org.example.proto.Test(this);
      int from_bitField0_ = bitField0_;
      result.mapFieldA_ = internalGetMapFieldA();
      result.mapFieldA_.makeImmutable();
      if (contentsBuilder_ == null) {
        result.contents_ = contents_;
      } else {
        result.contents_ = contentsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.proto.Test) {
        return mergeFrom((org.example.proto.Test)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.proto.Test other) {
      if (other == org.example.proto.Test.getDefaultInstance()) return this;
      internalGetMutableMapFieldA().mergeFrom(
          other.internalGetMapFieldA());
      if (other.hasContents()) {
        mergeContents(other.getContents());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.example.proto.Test parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.example.proto.Test) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> mapFieldA_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMapFieldA() {
      if (mapFieldA_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapFieldADefaultEntryHolder.defaultEntry);
      }
      return mapFieldA_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableMapFieldA() {
      onChanged();;
      if (mapFieldA_ == null) {
        mapFieldA_ = com.google.protobuf.MapField.newMapField(
            MapFieldADefaultEntryHolder.defaultEntry);
      }
      if (!mapFieldA_.isMutable()) {
        mapFieldA_ = mapFieldA_.copy();
      }
      return mapFieldA_;
    }

    public int getMapFieldACount() {
      return internalGetMapFieldA().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; map_field_a = 1;</code>
     */

    @java.lang.Override
    public boolean containsMapFieldA(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMapFieldA().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapFieldAMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMapFieldA() {
      return getMapFieldAMap();
    }
    /**
     * <code>map&lt;string, string&gt; map_field_a = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMapFieldAMap() {
      return internalGetMapFieldA().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; map_field_a = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getMapFieldAOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMapFieldA().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; map_field_a = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getMapFieldAOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMapFieldA().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMapFieldA() {
      internalGetMutableMapFieldA().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; map_field_a = 1;</code>
     */

    public Builder removeMapFieldA(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMapFieldA().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableMapFieldA() {
      return internalGetMutableMapFieldA().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; map_field_a = 1;</code>
     */
    public Builder putMapFieldA(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMapFieldA().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; map_field_a = 1;</code>
     */

    public Builder putAllMapFieldA(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMapFieldA().getMutableMap()
          .putAll(values);
      return this;
    }

    private org.example.proto.Test.Contents contents_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.example.proto.Test.Contents, org.example.proto.Test.Contents.Builder, org.example.proto.Test.ContentsOrBuilder> contentsBuilder_;
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     * @return Whether the contents field is set.
     */
    public boolean hasContents() {
      return contentsBuilder_ != null || contents_ != null;
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     * @return The contents.
     */
    public org.example.proto.Test.Contents getContents() {
      if (contentsBuilder_ == null) {
        return contents_ == null ? org.example.proto.Test.Contents.getDefaultInstance() : contents_;
      } else {
        return contentsBuilder_.getMessage();
      }
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     */
    public Builder setContents(org.example.proto.Test.Contents value) {
      if (contentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        contents_ = value;
        onChanged();
      } else {
        contentsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     */
    public Builder setContents(
        org.example.proto.Test.Contents.Builder builderForValue) {
      if (contentsBuilder_ == null) {
        contents_ = builderForValue.build();
        onChanged();
      } else {
        contentsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     */
    public Builder mergeContents(org.example.proto.Test.Contents value) {
      if (contentsBuilder_ == null) {
        if (contents_ != null) {
          contents_ =
            org.example.proto.Test.Contents.newBuilder(contents_).mergeFrom(value).buildPartial();
        } else {
          contents_ = value;
        }
        onChanged();
      } else {
        contentsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     */
    public Builder clearContents() {
      if (contentsBuilder_ == null) {
        contents_ = null;
        onChanged();
      } else {
        contents_ = null;
        contentsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     */
    public org.example.proto.Test.Contents.Builder getContentsBuilder() {
      
      onChanged();
      return getContentsFieldBuilder().getBuilder();
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     */
    public org.example.proto.Test.ContentsOrBuilder getContentsOrBuilder() {
      if (contentsBuilder_ != null) {
        return contentsBuilder_.getMessageOrBuilder();
      } else {
        return contents_ == null ?
            org.example.proto.Test.Contents.getDefaultInstance() : contents_;
      }
    }
    /**
     * <code>.test.Test.Contents contents = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.example.proto.Test.Contents, org.example.proto.Test.Contents.Builder, org.example.proto.Test.ContentsOrBuilder> 
        getContentsFieldBuilder() {
      if (contentsBuilder_ == null) {
        contentsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.example.proto.Test.Contents, org.example.proto.Test.Contents.Builder, org.example.proto.Test.ContentsOrBuilder>(
                getContents(),
                getParentForChildren(),
                isClean());
        contents_ = null;
      }
      return contentsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:test.Test)
  }

  // @@protoc_insertion_point(class_scope:test.Test)
  private static final org.example.proto.Test DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.proto.Test();
  }

  public static org.example.proto.Test getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Test>
      PARSER = new com.google.protobuf.AbstractParser<Test>() {
    @java.lang.Override
    public Test parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Test(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Test> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Test> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.proto.Test getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

